ktor:
    application:
        modules:
            - com.vocabutor.ApplicationKt.module
    deployment:
        port: 8080

postgres:
    url: $POSTGRES_URL
    user: $POSTGRES_USER
    pass: $POSTGRES_PASS
